environment_version: 1
credentials:
- type: aws
  id: 9aPerPrcI6HP7O
  description: 'aws read-only '
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: api-key
  id: XabxP0Ll49wwKM
  description: Codeocean test
  key: API_KEY
  secret: API_SECRET
